/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Application.coordonnateur;

import Application.BDD;
import Application.Parameter;
import Application.ResultSetTableModel;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.ImageIcon;
import javax.swing.JLabel;

/**
 *
 * @author hp
 */
public class GestionInscription extends javax.swing.JFrame {

    // Déclarations
    ResultSet rs, rs1, rs2, rs3;
    BDD db;
    int identifiant1, id_etudiant1, id_student1;
    String etat1 = null, etat2 = null;
    
    
    
    public GestionInscription() {
       db = new BDD(new Parameter().HOST_DB,new Parameter().USERNAME_DB, new Parameter().PASSWORD_DB,
        new Parameter().IPHOST, new Parameter().PORT);
        initComponents();
        jButton1.setIcon(new ImageIcon(getClass().getResource("/MesImages/retour.png")));
        jButton2.setIcon(new ImageIcon(getClass().getResource("/MesImages/imprimer3.png")));
        jButton5.setIcon(new ImageIcon(getClass().getResource("/MesImages/recherche.png")));
        table();
        
    }
    
    public void table(){
        String a[] = {"etudiant.identifiant","diplome.id_diplome", "contact.id_contact", "etudiant.prenom", "etudiant.nom", "etudiant.annee", "etudiant.departement", "diplome.annee", "diplome.mention", "diplome.etablissement",
                        "contact.prenom_contact", "contact.nom_contact"};
        rs1 = db.querySelectAll("etudiant");
        rs2 = db.querySelectAll("diplome");
        rs3 = db.querySelectAll("contact");
        
        try {
            
            while(rs1.next() && rs2.next() && rs3.next()){
                identifiant1 = rs1.getInt("identifiant");
                System.out.println(identifiant1);
                
                id_etudiant1 = rs2.getInt("id_etudiant");
                System.out.println(id_etudiant1);
                
                id_student1 = rs3.getInt("id_student");
                System.out.println(id_student1);
            }
            
        } catch (SQLException e) {
            System.err.println(e.getMessage());
        }
        
        //etat1 = (identifiant1 == id_etudiant1) ? true : false;
        //etat2 = (identifiant1 == id_student1) ? true : false;
        
        //etat1 += "(" +identifiant1+ "=" +id_etudiant1+ ") AND (" +identifiant1+ "="  +id_student1+ ")";
        //etat1 += "(etudiant.identifiant ='" +id_etudiant1+ "') AND (etudiant.identifiant='" +id_student1+ "')";
        etat1 = " FROM etudiant, diplome, contact WHERE etudiant.identifiant ='" +id_etudiant1+ "' and etudiant.identifiant='" +id_student1+ "'";
        //etat2 = "(" +identifiant1+ "==" +id_student1+ ")";
        
        /*if (etat1 == true && etat2 == true)
        {
           rs = db.querySelect(a,"etudiant", "diplome", "contact" ,etat1, etat2);
           table_inscription.setModel(new ResultSetTableModel(rs));

        }*/
        
        //rs = db.querySelect(a,"etudiant", "diplome", "contact" ,etat1);
        rs = db.querySelectIns(a,etat1);
        table_inscription.setModel(new ResultSetTableModel(rs));
       

        
        
    }


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        table_inscription = new javax.swing.JTable();
        jLabel16 = new javax.swing.JLabel();
        com_rech = new javax.swing.JComboBox();
        jButton5 = new javax.swing.JButton();
        txt_rech = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 51, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("GESTION DES INSCRIPTIONS");

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 102, 102));
        jButton1.setText("Retour Menu");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(171, 171, 171)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jButton1)
                .addGap(16, 16, 16)
                .addComponent(jLabel1)
                .addContainerGap(79, Short.MAX_VALUE))
        );

        table_inscription.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "identifiant", "id_diplome", "id_contact", "prenom", "nom", "annee", "departement", "annee", "mention", "etablissement", "prenom_contact", "nom_contact"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.Integer.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(table_inscription);

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Rechercher  : ");

        com_rech.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        com_rech.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "identifiant", "departement", "etablissement" }));
        com_rech.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                com_rechActionPerformed(evt);
            }
        });

        jButton5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 102, 102));
        jButton5.setText("recherche");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        txt_rech.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 102, 102));
        jButton2.setText("Imprimer");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(com_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1197, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(165, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(com_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txt_rech, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 370, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(252, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        MenuCoordonnateur coordonnateur = new MenuCoordonnateur();
        coordonnateur.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void com_rechActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_com_rechActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_com_rechActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed

        /*if(txt_rech.getText().equals("")){
            JOptionPane.showMessageDialog(this, "SVP entrez quelque chose");
        } else {
            if(com_rech.getSelectedItem().equals("id_diplome")){
                rs = db.querySelectAll("diplome", "id_diplome LIKE '%" +txt_rech.getText()+ "%'");
                table_diplome.setModel(new ResultSetTableModel(rs));

            } else if(com_rech.getSelectedItem().equals("id_etudiant")){
                rs = db.querySelectAll("diplome", "diplome LIKE '%" +txt_rech.getText()+ "%'");
                table_diplome.setModel(new ResultSetTableModel(rs));

            } else if(com_rech.getSelectedItem().equals("annee")){
                rs = db.querySelectAll("diplome", "annee LIKE '%" +txt_rech.getText()+ "%'");
                table_diplome.setModel(new ResultSetTableModel(rs));

            } else if(com_rech.getSelectedItem().equals("mention")){
                rs = db.querySelectAll("diplome", "mention LIKE '%" +txt_rech.getText()+ "%'");
                table_diplome.setModel(new ResultSetTableModel(rs));

            } else if(com_rech.getSelectedItem().equals("etablissement")){
                rs = db.querySelectAll("diplome", "etablissement LIKE '%" +txt_rech.getText()+ "%'");
                table_diplome.setModel(new ResultSetTableModel(rs));
            }
        }*/
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GestionInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GestionInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GestionInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GestionInscription.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GestionInscription().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox com_rech;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table_inscription;
    private javax.swing.JTextField txt_rech;
    // End of variables declaration//GEN-END:variables
}
